from app import app, db
from app import PincodeLocation  # Import only models and app, NOT pincodes

# Your pincode data
# pincode_data.py
pincodes = [
    {"pincode":"411014","location":"9 DRD","city":"Pune City"},
    {"pincode":"411040","location":"AFMC","city":"Pune City"},
    {"pincode":"411032","location":"Airport (Pune)","city":"Pune City"},
    {"pincode":"411035","location":"Akurdi","city":"Pune City"},
    {"pincode":"411003","location":"Ammunition Factory Khadki","city":"Pune City"},
    {"pincode":"411026","location":"Bhosari I.E.","city":"Pune City"},
    {"pincode":"411039","location":"Bhosarigoan","city":"Pune City"},
    {"pincode":"411037","location":"Bibvewadi","city":"Pune City"},
    {"pincode":"411001","location":"C D A (O)","city":"Pune City"},
    {"pincode":"411031","location":"C M E","city":"Pune City"},
    {"pincode":"411019","location":"Chinchwad East","city":"Pune City"},
    {"pincode":"411033","location":"Chinchwadgaon","city":"Pune City"},
    {"pincode":"411012","location":"Dapodi Bazar","city":"Pune City"},
    {"pincode":"411012","location":"Dapodi","city":"Pune City"},
    {"pincode":"411015","location":"Dhanori","city":"Pune City"},
    {"pincode":"411015","location":"Dighi Camp","city":"Pune City"},
    {"pincode":"411001","location":"Dr.B.A. Chowk","city":"Pune City"},
    {"pincode":"411014","location":"Dukirkline","city":"Pune City"},
    {"pincode":"411003","location":"East Khadki","city":"Pune City"},
    {"pincode":"411001","location":"Ghorpuri Bazar","city":"Pune City"},
    {"pincode":"411003","location":"H.E. Factory","city":"Pune City"},
    {"pincode":"411028","location":"Hadapsar","city":"Pune City"},
    {"pincode":"411013","location":"Hadpsar I.E.","city":"Pune City"},
    {"pincode":"411032","location":"Iaf Station","city":"Pune City"},
    {"pincode":"411026","location":"Indrayaninagar","city":"Pune City"},
    {"pincode":"411017","location":"Kalewadi","city":"Pune City"},
    {"pincode":"411034","location":"Kasarwadi","city":"Pune City"},
    {"pincode":"411003","location":"Khadki Bazar","city":"Pune City"},
    {"pincode":"411003","location":"Khadki","city":"Pune City"},
    {"pincode":"411048","location":"Khondhwa KH","city":"Pune City"},
    {"pincode":"411048","location":"Kondhwa BK","city":"Pune City"},
    {"pincode":"411048","location":"Kondhwa Lh","city":"Pune City"},
    {"pincode":"411047","location":"Lohogaon","city":"Pune City"},
    {"pincode":"411019","location":"M.Phulenagar","city":"Pune City"},
    {"pincode":"411037","location":"Market Yard (Pune)","city":"Pune City"},
    {"pincode":"411018","location":"Masulkar Colony","city":"Pune City"},
    {"pincode":"411060","location":"Mohamadwadi","city":"Pune City"},
    {"pincode":"411036","location":"Mundhva AV","city":"Pune City"},
    {"pincode":"411036","location":"Mundhva","city":"Pune City"},
    {"pincode":"411048","location":"N I B M","city":"Pune City"},
    {"pincode":"411001","location":"N.W. College","city":"Pune City"},
    {"pincode":"411018","location":"Nehrunagar (Pune)","city":"Pune City"},
    {"pincode":"411044","location":"P.C.N.T.","city":"Pune City"},
    {"pincode":"411017","location":"Pimpri Colony","city":"Pune City"},
    {"pincode":"411018","location":"Pimpri P F","city":"Pune City"},
    {"pincode":"411017","location":"Pimpri Waghire","city":"Pune City"},
    {"pincode":"411033","location":"Punawale","city":"Pune City"},
    {"pincode":"411001","location":"Pune Cantt East","city":"Pune City"},
    {"pincode":"411001","location":"Pune","city":"Pune City"},
    {"pincode":"411001","location":"Pune New Bazar","city":"Pune City"},
    {"pincode":"411062","location":"Rupeenagar","city":"Pune City"},
    {"pincode":"411001","location":"Sachapir Street","city":"Pune City"},
    {"pincode":"411037","location":"Salisbury Park","city":"Pune City"},
    {"pincode":"411027","location":"Sangavi","city":"Pune City"},
    {"pincode":"411028","location":"Sasanenagar","city":"Pune City"},
    {"pincode":"411022","location":"Srpf","city":"Pune City"},
    {"pincode":"411037","location":"T.V. Nagar","city":"Pune City"},
    {"pincode":"411062","location":"Talwade","city":"Pune City"},
    {"pincode":"411033","location":"Thathawade","city":"Pune City"},
    {"pincode":"411033","location":"Thergaon","city":"Pune City"},
    {"pincode":"411014","location":"Vadgaon Sheri","city":"Pune City"},
    {"pincode":"411032","location":"Vidyanagar (Pune)","city":"Pune City"},
    {"pincode":"411015","location":"Vishrantwadi","city":"Pune City"},
    {"pincode":"411057","location":"Wakad","city":"Pune City"},
    {"pincode":"411040","location":"Wanowarie","city":"Pune City"},
    {"pincode":"411044","location":"Yamunanagar","city":"Pune City"},
    {"pincode":"411006","location":"Yerwada","city":"Pune City"},
    {"pincode":"411006","location":"Yerwada T.S.","city":"Pune City"},
    {"pincode":"411004","location":"A.R. Shala","city":"Pune City"},
    {"pincode":"411051","location":"Anandnagar (Pune)","city":"Pune City"},
    {"pincode":"411021","location":"Armament","city":"Pune City"},
    {"pincode":"411007","location":"Aundh T.S.","city":"Pune City"},
    {"pincode":"411002","location":"Bajirao Road","city":"Pune City"},
    {"pincode":"411008","location":"Baner Road","city":"Pune City"},
    {"pincode":"411042","location":"Bhavani Peth","city":"Pune City"},
    {"pincode":"411038","location":"Bhusari Colony","city":"Pune City"},
    {"pincode":"411020","location":"Botanical Garden (Pune)","city":"Pune City"},
    {"pincode":"411005","location":"Congress House Road","city":"Pune City"},
    {"pincode":"411004","location":"Deccan Gymkhana","city":"Pune City"},
    {"pincode":"411043","location":"Dhankawadi","city":"Pune City"},
    {"pincode":"411038","location":"Ex. Serviceman Colony","city":"Pune City"},
    {"pincode":"411004","location":"Film Institute","city":"Pune City"},
    {"pincode":"411007","location":"Ganeshkhind","city":"Pune City"},
    {"pincode":"411042","location":"Ghorpade Peth","city":"Pune City"},
    {"pincode":"411016","location":"Govt. Polytechnic","city":"Pune City"},
    {"pincode":"411042","location":"Guruwar Peth","city":"Pune City"},
    {"pincode":"411002","location":"Kapad Ganj","city":"Pune City"},
    {"pincode":"411052","location":"Karvenagar","city":"Pune City"},
    {"pincode":"411011","location":"Kasba Peth","city":"Pune City"},
    {"pincode":"411046","location":"Katraj","city":"Pune City"},
    {"pincode":"411024","location":"Khadakwasla R.S.","city":"Pune City"},
    {"pincode":"411038","location":"Kothrud","city":"Pune City"},
    {"pincode":"411030","location":"Lokmanyanagar","city":"Pune City"},
    {"pincode":"411011","location":"Mangalwar Peth (Pune)","city":"Pune City"},
    {"pincode":"411016","location":"Model Colony","city":"Pune City"},
    {"pincode":"411008","location":"N.C.L. Pune","city":"Pune City"},
    {"pincode":"411023","location":"N.D.A. Khadakwasla","city":"Pune City"},
    {"pincode":"411045","location":"N.I.A.","city":"Pune City"},
    {"pincode":"411002","location":"Nana Peth","city":"Pune City"},
    {"pincode":"411030","location":"Narayan Peth","city":"Pune City"},
    {"pincode":"411052","location":"Navsahyadri","city":"Pune City"},
    {"pincode":"411009","location":"Parvati Gaon","city":"Pune City"},
    {"pincode":"411009","location":"Parvati","city":"Pune City"},
    {"pincode":"411002","location":"Pune City","city":"Pune City"},
    {"pincode":"411020","location":"Range Hills","city":"Pune City"},
    {"pincode":"411030","location":"Rashtra Bhasha Bhavan","city":"Pune City"},
    {"pincode":"411011","location":"Rasta Peth","city":"Pune City"},
    {"pincode":"411002","location":"Raviwar Peth","city":"Pune City"},
    {"pincode":"411030","location":"S.P. College","city":"Pune City"},
    {"pincode":"411005","location":"S.S.C.Exam Board","city":"Pune City"},
    {"pincode":"411030","location":"Sadashiv Peth","city":"Pune City"},
    {"pincode":"411030","location":"Shaniwar Peth (Pune)","city":"Pune City"},
    {"pincode":"411016","location":"Shivaji Housing Society","city":"Pune City"},
    {"pincode":"411005","location":"Shivajinagar (Pune)","city":"Pune City"},
    {"pincode":"411002","location":"Shukrawar Peth (Pune)","city":"Pune City"},
    {"pincode":"411042","location":"Swargate Chowk","city":"Pune City"},
    {"pincode":"411042","location":"Swargate","city":"Pune City"},
    {"pincode":"411041","location":"Vadgaon Budruk","city":"Pune City"},
    {"pincode":"411058","location":"Warje","city":"Pune City"},
]

# Insert logic
with app.app_context():
    for item in pincodes:
        exists = PincodeLocation.query.filter_by(pincode=item["pincode"]).first()
        if not exists:
            new_pin = PincodeLocation(
                pincode=item["pincode"],
                location=item["location"],
                city=item["city"]
            )
            db.session.add(new_pin)
    db.session.commit()
    print("✅ Pincode data inserted.")
